/** Homepage Core Features section — fixed order per product spec */
export const CORE_FEATURE_SLUGS = [
  "public-post",
  "photo-album",
  "video-post",
  "follow",
  "like",
  "comment",
  "share",
  "ranking",
  "vote",
  "gift",
  "wallet",
  "chat",
  "voice-call",
  "video-call",
  "live",
  "live-archive",
  "unlock-photo",
  "unlock-video",
  "subscription",
  "fan-club",
  "marketplace",
  "event",
  "contest",
  "creator-directory",
] as const;
